/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'assembleFinalLinkedInPost': EventHandler<{ generated_for: string }, { topic: 'final-linkedin-post-ready'; data: { finalPost: string; generated_for: string } }>
    'generateSeoKeywords': EventHandler<{ post: string; generated_for: string }, { topic: 'seo-keywords-generated'; data: { generated_for: string } }>
    'generateImageForLinkedInPost': EventHandler<{ post: string; generated_for: string }, { topic: 'image-generated-for-post'; data: { generated_for: string } }>
    'generateLinkedInPost': EventHandler<{ message: string; generated_for: string }, { topic: 'linkedin-post-generated'; data: { post: string; generated_for: string } }>
    'FinalLinkedInPost': EventHandler<{ finalPost: string; generated_for: string }, never>
    'getIdeaFromLLM': EventHandler<{ name: string }, { topic: 'idea-generated'; data: { message: string; generated_for: string } }>
    'LinkedIn Post Agent': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }>, { topic: 'get-topic-idea'; data: { name: string } }>
  }
}