/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'whatsapp-inbound-handler': ApiRouteHandler<{ entry: { changes: { value: { messages?: { from: string; text: { body: string } }[] } }[] }[] }, unknown, { topic: 'message-received'; data: { user: string; message: string } }>
    'send-whatsapp-message': EventHandler<{ message: string; user?: string }, never>
    'planner': EventHandler<{ user: string; type: 'meal' | 'workout'; prompt: string }, { topic: 'send-whatsapp-message-request'; data: { message: string; user?: string } }>
    'planner-api': ApiRouteHandler<{ user: string; type: 'meal' | 'workout'; prompt: string }, unknown, { topic: 'planner-request'; data: { user: string; type: 'meal' | 'workout'; prompt: string } }>
    'intent-router': ApiRouteHandler<{ user: string; message: string }, unknown, { topic: 'message-received'; data: { user: string; message: string } }>
    'log-confirmation': EventHandler<{ user: string }, { topic: 'send-whatsapp-message-request'; data: { message: string; user?: string } }>
    'log-activity-api': ApiRouteHandler<{ user: string; weight?: string; workout?: string; meal?: string }, unknown, { topic: 'user-activity-log'; data: { user: string; weight?: string; workout?: string; meal?: string } }>
    'log-user-activity': EventHandler<{ user: string; weight?: string; workout?: string; meal?: string }, never>
    'user-activity-extract': EventHandler<{ user: string; message: string }, { topic: 'user-activity-log'; data: { user: string; weight?: string; workout?: string; meal?: string } }>
    'classify-user-intent': EventHandler<{ user: string; message: string }, { topic: 'planner-request'; data: { user: string; type: 'meal' | 'workout'; prompt: string } } | { topic: 'user-activity-extract'; data: { user: string; message: string } } | { topic: 'analyze-user-habits'; data: { user: string } } | { topic: 'health-chat-message'; data: { message: string; conversationId?: string; assistantMessageId: string } }>
    'health-chat-api': ApiRouteHandler<{ message: string; conversationId?: string }, unknown, { topic: 'health-chat-message'; data: { message: string; conversationId?: string; assistantMessageId: string } }>
    'habit-analyzer': EventHandler<{ user: string }, { topic: 'send-whatsapp-message-request'; data: { message: string; user?: string } }>
    'analyzer-api': ApiRouteHandler<{ user: string }, unknown, { topic: 'analyze-user-habits'; data: { user: string } }>
    'ai-health-response': EventHandler<{ message: string; conversationId?: string; assistantMessageId: string }, { topic: 'send-whatsapp-message-request'; data: { message: string; user?: string } }>
  }
}