/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'retrieve-tweets-api': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: { type: 'classic' | 'listicle' | 'quote'; tweet: string; reason: string }[] }>, never>
    'processArticle': EventHandler<{ body: string }, never>
    'fetch devto articles': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }>, { topic: 'article.submitted'; data: { body: string } }>
  }
}