/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'Conversation Summarizer': EventHandler<{ fileCount: number; folderPath: string; transcriptionsPath: string; stateKey: string }, never>
    'Conversation Screenshot Transcriber': EventHandler<{ imageCount: number; folderPath: string; stateKey: string }, never>
    'Conversation Screenshot Reader': EventHandler<{ folderPath: string; traceId: string }, { topic: 'conversation-reader-complete'; data: { imageCount: number; folderPath: string; stateKey: string } }>
    'Conversation Reader Trigger': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'conversation-reader-start'; data: { folderPath: string; traceId: string } }>
  }
}