/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'Status Tracker': EventHandler<never, never>
    'Smart Uptime Monitor': CronHandler<never>
    'Health Check': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Dashboard': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Status API': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Smart Alerter': EventHandler<never, never>
  }
}