/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdateFeed': EventHandler<never, never>
    'SupabaseSync': EventHandler<never, never>
    'NotifyOwner': EventHandler<never, never>
    'LikeApi': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; postId: string; traceId: string; alreadyLiked?: boolean }> | ApiResponse<400, { error: string; message: string }> | ApiResponse<500, { error: string; message: string }>, { topic: 'like:post'; data: never }>
    'FirebaseNotification': EventHandler<never, never>
    'EnqueueSideEffects': EventHandler<never, { topic: 'like:notify-owner'; data: never } | { topic: 'like:update-feed'; data: never } | { topic: 'like:firebase-notification'; data: never }>
  }
}